# Nội dung các bài viết blog Sách nhà Harry
# Mỗi khối: ("p", text) | ("h2", text) | ("ul", [..]) | ("ol", [..]) | ("quote", text) | ("tip", text) | ("table", [[hdr...],[row...],...])

ARTICLES = [
{
 "slug": "dau-hieu-bi-thao-tung-tam-ly",
 "title": "8 dấu hiệu bạn đang bị thao túng tâm lý trong một mối quan hệ",
 "desc": "Thao túng tâm lý (gaslighting) khiến bạn nghi ngờ chính trí nhớ và cảm xúc của mình. Đây là 8 dấu hiệu dễ nhận ra và cách tự bảo vệ bản thân.",
 "cat": "Nhận diện con người",
 "date": "2026-09-29",
 "fig": "think",
 "quiz": ("thaotung", "Làm bài test: Bạn có đang bị thao túng tâm lý?"),
 "body": [
  ("p", "Có những mối quan hệ không có cãi vã lớn, không có lời lẽ nặng nề, nhưng càng ở lâu bạn càng thấy mình nhỏ lại. Bạn bắt đầu nghi ngờ trí nhớ của chính mình, xin lỗi nhiều hơn, và không còn chắc điều mình cảm thấy là đúng hay sai. Đó thường là dấu hiệu của thao túng tâm lý."),
  ("p", "Trong tiếng Anh, kiểu thao túng khiến người khác nghi ngờ nhận thức của chính họ được gọi là gaslighting. Cái tên này bắt nguồn từ vở kịch \"Gas Light\" năm 1938 và bộ phim cùng tên năm 1944, kể về một người chồng cố tình làm vợ tin rằng cô đang mất trí. Ngày nay, từ này được dùng rộng rãi để mô tả những hành vi làm người khác mất niềm tin vào cảm nhận của mình."),
  ("p", "Dưới đây là 8 dấu hiệu thường gặp. Một vài dấu hiệu riêng lẻ chưa chắc đã là thao túng, vì ai cũng có lúc cư xử chưa khéo. Điều đáng để ý là khi chúng lặp lại thành một khuôn mẫu."),
  ("h2", "1. Bạn thường xuyên nghi ngờ trí nhớ của mình"),
  ("p", "Bạn nhớ rõ người đó đã nói một câu, nhưng họ khẳng định chắc nịch là không hề nói. Lần một, bạn nghĩ mình nhầm. Lần thứ mười, bạn bắt đầu tin rằng trí nhớ của mình có vấn đề. Đây là dấu hiệu cốt lõi nhất: cảm giác \"chắc mình sai rồi\" xuất hiện ngày càng nhiều."),
  ("h2", "2. Cảm xúc của bạn luôn bị gạt đi"),
  ("p", "\"Em nhạy cảm quá.\" \"Có gì đâu mà làm quá lên.\" Những câu này, khi lặp lại đủ nhiều, dạy bạn rằng cảm xúc của mình không đáng tin. Người tôn trọng bạn có thể không đồng ý, nhưng họ vẫn muốn hiểu vì sao bạn buồn."),
  ("h2", "3. Bạn xin lỗi cả khi không biết mình sai ở đâu"),
  ("p", "Mỗi cuộc tranh luận đều kết thúc bằng việc bạn xin lỗi, dù lúc bắt đầu bạn mới là người bị tổn thương. Dần dần, xin lỗi trở thành phản xạ để giữ yên ổn, không còn là vì bạn thực sự làm sai."),
  ("h2", "4. Lúc ngọt ngào, lúc lạnh nhạt không lý do"),
  ("p", "Người đó có thể rất ấm áp, rồi đột ngột im lặng, lạnh lùng mà không giải thích. Sự thất thường này khiến bạn luôn trong trạng thái cố gắng lấy lại \"phiên bản tốt\" của họ, và vô tình càng gắn chặt hơn vào mối quan hệ."),
  ("h2", "5. Bạn dần xa bạn bè và gia đình"),
  ("p", "Không phải lúc nào cũng là cấm đoán trực tiếp. Có khi chỉ là những lời chê nhẹ về bạn bè bạn, những lần tỏ ra khó chịu khi bạn ra ngoài. Kết quả là vòng tròn của bạn nhỏ dần, và người đó trở thành nguồn góc nhìn duy nhất."),
  ("h2", "6. Lỗi cũ của bạn luôn bị lôi ra"),
  ("p", "Mỗi khi bạn góp ý điều gì, câu chuyện lại quay về một lỗi cũ của bạn. Cuộc nói chuyện chuyển từ \"việc này có ổn không\" sang \"bạn cũng từng như thế\", và vấn đề ban đầu không bao giờ được giải quyết."),
  ("h2", "7. Lời hứa nhiều, hành động ít, người bị trách vẫn là bạn"),
  ("p", "Họ hứa sẽ thay đổi, rồi không làm. Khi bạn nhắc lại, bạn bị xem là người khó tính, hay đòi hỏi. Khoảng cách giữa lời nói và hành động là một trong những thước đo rõ ràng nhất về một người."),
  ("h2", "8. Bạn không còn biết mình thật sự muốn gì"),
  ("p", "Mọi quyết định, từ việc lớn đến việc nhỏ, bạn đều phải đoán xem người đó sẽ phản ứng thế nào. Khi được hỏi \"bạn muốn gì\", bạn thấy trống rỗng. Đây là lúc tiếng nói bên trong bạn đã bị thu nhỏ quá nhiều."),
  ("h2", "Làm gì nếu bạn nhận ra mình trong những dấu hiệu này?"),
  ("ul", [
    "Ghi chép lại. Viết ngắn gọn sự việc, ngày giờ và lời nói. Việc này giúp bạn giữ vững trí nhớ của mình khi bị phủ nhận.",
    "Hỏi một người ngoài cuộc. Kể lại với một người bạn tin tưởng. Góc nhìn từ bên ngoài thường rõ ràng hơn rất nhiều.",
    "Đặt một giới hạn nhỏ và quan sát. Ví dụ: \"Mình không muốn nói chuyện khi bị gọi là làm quá.\" Cách người đó phản ứng sẽ cho bạn biết nhiều điều.",
    "Kết nối lại với những người thân của mình. Đừng đối diện chuyện này một mình.",
    "Cân nhắc gặp chuyên gia tâm lý nếu cảm giác nghi ngờ bản thân kéo dài và ảnh hưởng đến cuộc sống."
  ]),
  ("tip", "Nếu bạn cảm thấy không an toàn hoặc bị đe dọa, hãy ưu tiên sự an toàn của mình trước tiên: tìm đến người bạn tin tưởng, gia đình, hoặc liên hệ cơ quan chức năng nơi bạn sống."),
  ("p", "Cảm giác của bạn là thật. Việc bạn đang đọc bài này và tự đặt câu hỏi đã là một bước quan trọng để lấy lại tiếng nói của chính mình."),
 ]
},
{
 "slug": "5-thoi-quen-cua-nguoi-ky-luat",
 "title": "5 thói quen âm thầm của người kỷ luật (và cách bắt đầu từ hôm nay)",
 "desc": "Người kỷ luật thật sự hiếm khi khoe mình kỷ luật. Đây là 5 thói quen âm thầm họ làm mỗi ngày và kế hoạch 7 ngày để bạn bắt đầu.",
 "cat": "Tư duy & kỷ luật",
 "date": "2026-09-28",
 "fig": "rise",
 "quiz": ("kyluat", "Làm bài test: Mức độ kỷ luật của bạn đến đâu?"),
 "body": [
  ("p", "Người thực sự kỷ luật thường chẳng bao giờ khoe mình kỷ luật. Bạn sẽ không thấy họ đăng ảnh đồng hồ 5 giờ sáng mỗi ngày. Bạn chỉ thấy kết quả: công việc xong đúng hẹn, cơ thể khỏe hơn, tài chính gọn gàng hơn, và một sự bình thản rất khó giả vờ."),
  ("p", "Điều thú vị là kỷ luật của họ không đến từ ý chí phi thường. Nó đến từ vài thói quen nhỏ, lặp lại đủ lâu để trở thành con người họ. Dưới đây là 5 thói quen như vậy."),
  ("h2", "1. Dậy sớm để có một giờ yên tĩnh"),
  ("p", "Họ không dậy sớm để chứng minh điều gì. Họ dậy sớm vì đó là khoảng thời gian duy nhất trong ngày không ai đòi hỏi gì ở họ: không tin nhắn, không cuộc họp, không tiếng ồn. Một giờ đó dùng để đọc, để nghĩ, để làm việc quan trọng nhất."),
  ("p", "Nếu bạn không phải người thích dậy sớm, điểm mấu chốt không nằm ở con số 5 giờ. Điểm mấu chốt là có một khoảng thời gian cố định, được bảo vệ, dành cho chính bạn."),
  ("h2", "2. Làm việc khó nhất trước"),
  ("p", "Ý chí giống như pin điện thoại: đầy nhất vào đầu ngày và cạn dần sau mỗi quyết định. Người kỷ luật dùng phần pin đầy đó cho việc khó nhất, thay vì tiêu nó vào việc lướt mạng hay trả lời tin nhắn."),
  ("p", "Khi việc khó nhất đã xong trước buổi trưa, phần còn lại của ngày nhẹ hẳn. Bạn không còn mang cảm giác nặng nề của một việc treo lơ lửng."),
  ("h2", "3. Nói \"không\" một cách nhẹ nhàng"),
  ("p", "Mỗi lời \"có\" với một việc không quan trọng là một lời \"không\" với việc quan trọng. Người kỷ luật hiểu điều đó, nên họ từ chối rõ ràng mà không cần giải thích dài dòng: \"Cảm ơn bạn, nhưng lần này mình không tham gia được.\""),
  ("p", "Họ cũng biết nói \"không\" với chính mình: với chiếc điện thoại lúc đang làm việc, với món đồ mua theo cảm hứng, với việc thức khuya không cần thiết."),
  ("h2", "4. Không chờ có động lực"),
  ("p", "Đây là khác biệt lớn nhất. Người bình thường làm khi có hứng. Người kỷ luật làm vì đã hẹn với chính mình. Có hứng hay không, việc vẫn phải xong, dù chỉ là một phiên bản nhỏ hơn."),
  ("quote", "Động lực là thứ đến sau khi bạn bắt đầu, không phải trước đó."),
  ("p", "Những ngày không có hứng là những ngày quyết định. Làm được một phiên bản nhỏ trong những ngày đó quan trọng hơn làm thật nhiều trong những ngày đầy hứng khởi."),
  ("h2", "5. Mỗi tối dành 5 phút nhìn lại"),
  ("p", "Trước khi ngủ, họ tự hỏi vài câu đơn giản: Hôm nay mình làm tốt điều gì? Điều gì chưa ổn? Ngày mai ba việc quan trọng nhất là gì?"),
  ("p", "Chỉ 5 phút, nhưng nó biến mỗi ngày thành một bài học thay vì một ngày trôi qua. Sau vài tháng, khoảng cách giữa người làm việc này và người không làm là rất lớn."),
  ("h2", "Kế hoạch 7 ngày để bắt đầu"),
  ("p", "Đừng cố áp dụng cả 5 thói quen cùng lúc. Hãy thêm dần từng thứ một:"),
  ("table", [
    ["Ngày", "Việc cần làm"],
    ["1", "Viết ra 3 việc quan trọng cho ngày mai trước khi ngủ."],
    ["2", "Làm việc khó nhất trong 30 phút đầu tiên khi bắt đầu làm việc."],
    ["3", "Để điện thoại ngoài tầm tay trong một phiên làm việc 25 phút."],
    ["4", "Từ chối một lời mời hoặc việc không quan trọng."],
    ["5", "Dậy sớm hơn thường lệ 20 phút và dùng cho riêng bạn."],
    ["6", "Làm một phiên bản nhỏ của thói quen dù không có hứng."],
    ["7", "Dành 5 phút nhìn lại cả tuần: điều gì dễ, điều gì khó."],
  ]),
  ("p", "Kỷ luật lúc đầu có thể nặng nề. Nhưng dần dần, nó cho bạn thứ quý giá nhất: quyền tự quyết về thời gian và cuộc sống của mình."),
 ]
},
{
 "slug": "quy-tac-2-phut-xay-thoi-quen",
 "title": "Quy tắc 2 phút: xây thói quen khi bạn chẳng có chút động lực nào",
 "desc": "Vì sao những quyết tâm lớn thường thất bại, và cách quy tắc 2 phút từ cuốn Atomic Habits giúp bạn bắt đầu một thói quen mới dễ dàng.",
 "cat": "Bài học từ sách",
 "date": "2026-09-27",
 "fig": "read",
 "quiz": ("kyluat", "Làm bài test: Mức độ kỷ luật của bạn đến đâu?"),
 "body": [
  ("p", "Đầu năm, bạn quyết tâm mỗi ngày đọc 50 trang sách, chạy 5 cây số, học tiếng Anh một tiếng. Tuần đầu rất hăng hái. Tuần thứ hai bắt đầu hụt hơi. Đến tuần thứ ba, mọi thứ dừng lại, kèm theo cảm giác mình là người thiếu ý chí."),
  ("p", "Vấn đề thường không nằm ở ý chí. Vấn đề nằm ở chỗ bạn bắt đầu quá lớn."),
  ("h2", "Quy tắc 2 phút là gì?"),
  ("p", "Trong cuốn Atomic Habits (bản tiếng Việt: Thay đổi tí hon, hiệu quả bất ngờ), tác giả James Clear gợi ý một nguyên tắc rất đơn giản: khi bắt đầu một thói quen mới, hãy thu nhỏ nó thành phiên bản làm được trong vòng 2 phút."),
  ("table", [
    ["Thói quen bạn muốn", "Phiên bản 2 phút"],
    ["Đọc sách mỗi ngày", "Đọc một trang"],
    ["Tập thể dục", "Mang giày chạy vào"],
    ["Học tiếng Anh", "Học 3 từ mới"],
    ["Viết nhật ký", "Viết một câu"],
    ["Dọn nhà gọn gàng", "Gấp một cái áo"],
  ]),
  ("p", "Nghe có vẻ quá dễ, thậm chí buồn cười. Nhưng đó chính là mục đích."),
  ("h2", "Vì sao cách này hiệu quả?"),
  ("p", "Ý tưởng cốt lõi là: một thói quen phải được thiết lập trước khi nó có thể được cải thiện. Bạn không thể nâng cấp một thói quen chưa tồn tại. Phiên bản 2 phút giúp bạn luyện kỹ năng quan trọng nhất: có mặt mỗi ngày."),
  ("p", "Ngoài ra, phần khó nhất của hầu hết mọi việc là bắt đầu. Khi đã mang giày vào, việc bước ra cửa và chạy vài phút dễ hơn nhiều so với việc đang nằm trên giường và nghĩ về 5 cây số."),
  ("quote", "Hãy làm cho việc bắt đầu dễ đến mức bạn không thể từ chối."),
  ("h2", "Những cái bẫy thường gặp"),
  ("ul", [
    "Tự ép mình làm nhiều hơn quá sớm. Những tuần đầu, dừng ở 2 phút cũng được. Mục tiêu là sự đều đặn, không phải khối lượng.",
    "Coi phiên bản nhỏ là \"gian lận\". Đọc một trang không phải là thất bại. Đó là bằng chứng bạn là người đọc sách mỗi ngày.",
    "Bỏ hẳn khi lỡ một ngày. Ai cũng có ngày bận rộn hay mệt mỏi. Điều quan trọng là không để lỡ hai ngày liên tiếp.",
  ]),
  ("h2", "Không bỏ lỡ hai lần"),
  ("p", "James Clear cũng nhấn mạnh một nguyên tắc đi kèm: đừng bao giờ bỏ lỡ hai lần liên tiếp. Lỡ một ngày là tai nạn. Lỡ hai ngày là khởi đầu của một thói quen mới, thói quen bỏ cuộc."),
  ("p", "Vào những ngày tệ nhất, hãy làm phiên bản 2 phút. Nó giữ cho chuỗi của bạn không bị đứt, và giữ cho bạn danh tính của một người không bỏ cuộc."),
  ("h2", "Bắt đầu ngay hôm nay"),
  ("ol", [
    "Chọn đúng một thói quen bạn muốn xây.",
    "Viết ra phiên bản 2 phút của nó.",
    "Gắn nó vào một việc bạn đã làm mỗi ngày, ví dụ: \"Sau khi pha cà phê buổi sáng, mình sẽ đọc một trang sách.\"",
    "Đánh dấu mỗi ngày bạn làm được. Nhìn chuỗi ngày dài dần là một phần thưởng rất thật.",
  ]),
  ("p", "Những thay đổi lớn hiếm khi đến từ một quyết tâm lớn. Chúng đến từ những việc nhỏ đến mức gần như không đáng kể, được lặp lại đủ lâu."),
 ]
},
]
